Repository nyeongha/stampee, pull requests merged in 2024-08, with the labels that each got.

#84 [FIX] : stamp page 디자인 변경
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/resources/fxml/keypadView.fxml
  project/stampee/src/main/resources/fxml/stamp.fxml
  project/stampee/src/main/resources/image/github_logo.png
  project/stampee/src/main/resources/image/github_logo_gray.png
  project/stampee/src/main/resources/image/github_logo_rec.png
  project/stampee/src/main/resources/image/java_logo.png
Labels: FIX💊, FE

#90 [FEAT]: 별점 표시 추가, 로고 누르면 화면 이동
  project/stampee/.idea/gradle.xml
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/ConnectionClose.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/controller/NumberPadController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/ShareCompleteController.java
  project/stampee/src/main/java/controller/ShareFailController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/controller/UserSignupController.java
  project/stampee/src/main/java/dto/response/ExpiredCouponDto.java
  project/stampee/src/main/java/exception/ErrorMessage.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/CouponService.java
  project/stampee/src/main/java/service/MailService.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/main/java/util/PasswordUtil.java
  project/stampee/src/main/java/view/CouponView.java
  project/stampee/src/main/java/view/PopupView.java
  project/stampee/src/main/java/view/ReviewView.java
  project/stampee/src/main/resources/css/CouponPage.css
  project/stampee/src/main/resources/css/common.css
  project/stampee/src/main/resources/fxml/keypadView.fxml
  project/stampee/src/main/resources/fxml/reviewListView.fxml
  project/stampee/src/main/resources/fxml/reviews.fxml
  project/stampee/src/main/resources/fxml/shareComplete.fxml
  project/stampee/src/main/resources/fxml/shareFailed.fxml
  project/stampee/src/main/resources/fxml/stamp.fxml
  project/stampee/src/main/resources/image/star.png
  project/stampee/src/main/resources/templates/reusables/Header.fxml
  project/stampee/src/test/java/repository/CouponRepositoryTest.java
  project/stampee/src/test/java/service/CouponServiceTest.java
  project/stampee/src/test/java/service/StampServiceTest.java
Labels: FEAT🍒, REFACTOR🎀, BE

#91 [FEAT]: CREATE REVIEW 뷰 생성 및 구현
  project/stampee/src/main/java/controller/CreateReviewController.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/resources/css/createReview.css
  project/stampee/src/main/resources/fxml/CreateReview.fxml
Labels: FEAT🍒, BE, FE

#87 [REFACTOR] : 지도 동적 출력
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/resources/css/modern-style.css
  project/stampee/src/main/resources/fxml/MapOutput.fxml
  project/stampee/src/main/resources/fxml/keypadView.fxml
  project/stampee/src/main/resources/fxml/stamp.fxml
  project/stampee/src/main/resources/image/github_logo_gray.png
  project/stampee/src/main/resources/image/github_logo_rec.png
  project/stampee/src/main/resources/image/java_logo.png
Labels: REFACTOR🎀, BE

#67 [FEAT]: 카페 점주회원 인덱스 페이지 추가
  .idea/checkstyle-idea.xml
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/CafeMainPageController.java
  project/stampee/src/main/java/controller/CafeSignupController.java
  project/stampee/src/main/java/dto/response/CafeMemberInfoDto.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/java/service/MemberService.java
  project/stampee/src/main/java/session/MemberSession.java
  project/stampee/src/main/resources/css/CafeMainPage.css
  project/stampee/src/main/resources/fxml/account/CafeSignUpPage.fxml
  project/stampee/src/main/resources/fxml/account/CafeSignupPage.fxml
  project/stampee/src/main/resources/fxml/account/LoginPage.fxml
  project/stampee/src/main/resources/fxml/account/SignUpPageMain.fxml
  project/stampee/src/main/resources/fxml/account/UserSignUpPage.fxml
  project/stampee/src/main/resources/fxml/account/UserSignupPage.fxml
  project/stampee/src/main/resources/fxml/index/CafeMainPage.fxml
  project/stampee/src/main/resources/fxml/reusables/Header.fxml
  project/stampee/src/main/resources/fxml/reusables/LogoArea.fxml
  project/stampee/src/main/resources/fxml/reusables/footer.fxml
  project/stampee/src/main/resources/image/default_profile_picture.jpg
Labels: FEAT🍒

#94 [FIX]: 지도 오류 수정, 리뷰 페이지 디자인 수정
  project/stampee/.idea/gradle.xml
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/build.gradle
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/CreateReviewController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/controller/NumberPadController.java
  project/stampee/src/main/java/controller/SignupMainController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Coupon.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/domain/Signature.java
  project/stampee/src/main/java/domain/Stamp.java
  project/stampee/src/main/java/dto/response/CafeMemberInfoDto.java
  project/stampee/src/main/java/dto/response/ExpiredCouponDto.java
  project/stampee/src/main/java/dto/response/LoggedCafeDto.java
  project/stampee/src/main/java/dto/response/LoggedMemberDto.java
  project/stampee/src/main/java/dto/response/MyCouponDto.java
  project/stampee/src/main/java/dto/response/MyStampDto.java
  project/stampee/src/main/java/exception/ErrorMessage.java
  project/stampee/src/main/java/formatter/MailMessageFormatter.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/java/service/CouponService.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/java/service/MemberService.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/main/java/service/UserService.java
  project/stampee/src/main/java/view/ReviewView.java
  project/stampee/src/main/resources/css/CouponPage.css
  project/stampee/src/main/resources/css/common.css
  project/stampee/src/main/resources/css/modern-style.css
  project/stampee/src/main/resources/fxml/CouponPage.fxml
  project/stampee/src/main/resources/fxml/CreateReview.fxml
  project/stampee/src/main/resources/fxml/MapOutput.fxml
  project/stampee/src/main/resources/fxml/keypadView.fxml
  project/stampee/src/main/resources/fxml/reviews.fxml
  project/stampee/src/main/resources/fxml/stamp.fxml
Labels: FEAT🍒, FIX💊, FE

#95 [FEAT]: 카페 메인 페이지 구현 완료
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CafeMainPageController.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/resources/fxml/index/CafeMainPage.fxml
Labels: FEAT🍒

#98 [FIX]: GIT 충돌 해결
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
Labels: FIX💊

#99 [FIX] 헤더 다시 추가
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/resources/css/CafeMainPage.css
  project/stampee/src/main/resources/css/CouponPage.css
  project/stampee/src/main/resources/css/login.css
Labels: FEAT🍒, REFACTOR🎀, BE

#106 [FEAT]: 세션 사용하도록 구현, [STYLE]: 사용 안하는 메서드, 클래스 삭제
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/CafeMainPageController.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/CreateReviewController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/controller/MemberLoginController.java
  project/stampee/src/main/java/controller/MemberSignupController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/SignupController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/dto/response/CafeMemberInfoDto.java
  project/stampee/src/main/java/dto/response/ExpiredCouponDto.java
  project/stampee/src/main/java/dto/response/LoggedCafeDto.java
  project/stampee/src/main/java/dto/response/LoggedMemberDto.java
  project/stampee/src/main/java/dto/response/MyCouponDto.java
  project/stampee/src/main/java/dto/response/MyStampDto.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/java/service/MemberService.java
  project/stampee/src/main/java/session/CafeSession.java
  project/stampee/src/main/java/session/MemberSession.java
  project/stampee/src/main/java/util/Encrypt.java
  project/stampee/src/main/java/util/PasswordUtil.java
  project/stampee/src/main/resources/css/CouponPage.css
  project/stampee/src/main/resources/css/modern-style.css
Labels: FEAT🍒, REFACTOR🎀, FE

#109 [FEAT]: 주석 제거
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/ReviewController.java
Labels: REFACTOR🎀

#114 [FIX]: SIGNUP, LOGIN PAGE ERROR 처리
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/LoginMainController.java
  project/stampee/src/main/java/session/MemberSession.java
  project/stampee/src/main/resources/fxml/account/CafeLoginPage.fxml
  project/stampee/src/main/resources/fxml/account/LoginPageMain.fxml
  project/stampee/src/main/resources/fxml/account/SignUpPageMain.fxml
  project/stampee/src/main/resources/fxml/reusables/Header.fxml
Labels: FIX💊, BE, FE

#116 [STYLE]: SignUpPageMain CSS EDIT
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/resources/fxml/account/SignUpPageMain.fxml
  project/stampee/src/main/resources/fxml/index/CafeMainPage.fxml
  project/stampee/src/main/resources/fxml/reusables/LogoArea.fxml
Labels: FE

#117 [FEAT]: login service 내부에서 cafe 생성하는 부분 아이디도 전달 받도록 수정
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/MemberLoginController.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/CafeService.java
Labels: FEAT🍒, REFACTOR🎀, BE

#120 [REFACTOR] : 적립하기 버튼 추가
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CafeMainPageController.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/CreateReviewController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/controller/MemberMainController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/dto/response/MyStampDto.java
  project/stampee/src/main/java/service/CouponService.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/resources/css/CafeMainPage.css
  project/stampee/src/main/resources/css/header.css
  project/stampee/src/main/resources/fxml/index/CafeMainPage.fxml
  project/stampee/src/main/resources/image/default_profile_picture.jpg
  project/stampee/src/main/resources/image/noprofile.png
Labels: FEAT🍒, BE, FE

#121 [FEAT]: 사용 안하는 메서드 정리
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/CafeSignupController.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/CreateReviewController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/controller/LoginMainController.java
  project/stampee/src/main/java/controller/MemberLoginController.java
  project/stampee/src/main/java/controller/MemberSignupController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/SignupController.java
  project/stampee/src/main/java/controller/SignupMainController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/session/CafeSession.java
  project/stampee/src/main/java/util/Popup.java
  project/stampee/src/main/java/util/SceneNavigator.java
  project/stampee/src/main/resources/fxml/shareComplete.fxml
Labels: REFACTOR🎀

#123 [FIX] : 충돌 해결
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CafeHeaderController.java
  project/stampee/src/main/java/controller/MemberMainPageController.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/resources/css/CafeMainPage.css
  project/stampee/src/main/resources/css/header.css
  project/stampee/src/main/resources/css/loginPage.css
  project/stampee/src/main/resources/fxml/account/CafeLoginPage.fxml
  project/stampee/src/main/resources/fxml/account/LoginPageMain.fxml
  project/stampee/src/main/resources/fxml/account/MemberLoginPage.fxml
  project/stampee/src/main/resources/fxml/index/CafeMainPage.fxml
  project/stampee/src/main/resources/fxml/reusables/CafeHeader.fxml
Labels: FIX💊, FE

#124 [STYLE]: SignupPage, LoginPage css modify
  project/stampee/src/main/java/controller/MemberMainPageController.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/resources/fxml/account/CafeSignupPage.fxml
  project/stampee/src/main/resources/fxml/account/MemberSignupPage.fxml
Labels: FE

#125 [STYLE]: 카페 회원가입 로고 수정
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/MemberLoginController.java
  project/stampee/src/main/java/controller/MemberMainPageController.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/main/java/util/SceneNavigator.java
  project/stampee/src/main/java/view/CouponView.java
  project/stampee/src/main/resources/css/CouponPage.css
  project/stampee/src/main/resources/fxml/account/CafeLoginPage.fxml
  project/stampee/src/main/resources/fxml/account/CafeSignupPage.fxml
  project/stampee/src/main/resources/fxml/account/LoginPageMain.fxml
  project/stampee/src/main/resources/fxml/account/MemberLoginPage.fxml
  project/stampee/src/main/resources/fxml/reusables/LogoArea.fxml
Labels: REFACTOR🎀, FE

#126 [FIX] : 충돌해결
  project/stampee/src/main/java/controller/MemberMainPageController.java
  project/stampee/src/main/java/repository/MemberRepository.java
Labels: FIX💊, BE

#127 [FIX]: 사용 안하는 클래스 삭제
  project/stampee/src/main/java/controller/MemberMainController.java
  project/stampee/src/main/java/controller/MemberMainPageController.java
  project/stampee/src/main/resources/css/memberMainPage.css
  project/stampee/src/main/resources/fxml/index/MemberMainPage.fxml
Labels: FIX💊

#129 [FEAT] : 카페 바로가기 기능 추가
  project/stampee/src/main/java/controller/MemberMainPageController.java
  project/stampee/src/main/resources/css/CafeMainPage.css
  project/stampee/src/main/resources/fxml/index/CafeMainPage.fxml
  project/stampee/src/main/resources/fxml/index/MemberMainPage.fxml
Labels: FEAT🍒, BE, FE

#130 [STYLE]: CafeMainPage 디자인 수정
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/ConnectionClose.java
  project/stampee/src/main/java/controller/CafeHeaderController.java
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/CafeMainPageController.java
  project/stampee/src/main/java/controller/CafeSignupController.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/CreateReviewController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/controller/LoginMainController.java
  project/stampee/src/main/java/controller/MemberLoginController.java
  project/stampee/src/main/java/controller/MemberMainPageController.java
  project/stampee/src/main/java/controller/MemberSignupController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/SignupMainController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/service/MemberService.java
  project/stampee/src/main/java/session/CafeSession.java
  project/stampee/src/main/java/util/Popup.java
  project/stampee/src/main/java/validation/ReviewValidationResult
  project/stampee/src/main/resources/css/cafeMainPage.css
  project/stampee/src/main/resources/css/couponPage.css
  project/stampee/src/main/resources/fxml/account/cafeLoginPage.fxml
  project/stampee/src/main/resources/fxml/account/cafeSignupPage.fxml
  project/stampee/src/main/resources/fxml/account/loginPageMain.fxml
  project/stampee/src/main/resources/fxml/account/memberLoginPage.fxml
  project/stampee/src/main/resources/fxml/account/memberSignupPage.fxml
  project/stampee/src/main/resources/fxml/account/signUpPageMain.fxml
  project/stampee/src/main/resources/fxml/couponPage.fxml
  project/stampee/src/main/resources/fxml/createReview.fxml
  project/stampee/src/main/resources/fxml/index/cafeMainPage.fxml
  project/stampee/src/main/resources/fxml/index/memberMainPage.fxml
  project/stampee/src/main/resources/fxml/mapOutput.fxml
  project/stampee/src/main/resources/fxml/reusables/cafeHeader.fxml
  project/stampee/src/main/resources/fxml/reusables/header.fxml
  project/stampee/src/main/resources/fxml/reusables/logoArea.fxml
  project/stampee/src/main/resources/fxml/reviews.fxml
  project/stampee/src/main/resources/fxml/stamp.fxml
  project/stampee/src/test/java/repository/CouponRepositoryTest.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
  project/stampee/src/test/java/service/CouponServiceTest.java
  project/stampee/src/test/java/service/StampServiceTest.java
Labels: REFACTOR🎀, FE

#131 [DOCS]: Update README.md
  README.md
Labels: DOCS✒️

#132 [FEAT]: main 주석 제거, 스케줄러 추가
  project/stampee/src/main/java/Main.java
Labels: FEAT🍒, FIX💊, BE
