Repository nyeongha/stampee, pull requests merged in 2024-07, with the labels that each got.

#1 [FEAT]: domain 패키지 추가
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/stampee.iml
  .idea/vcs.xml
  stampee/.gitignore
  stampee/.idea/.gitignore
  stampee/src/Main.java
  stampee/src/domain/Stamp.java
Labels: FEAT🍒

#2 프로젝트, domain 패키지 생성
  project/.idea/.gitignore
  project/.idea/misc.xml
  project/.idea/modules.xml
  project/.idea/vcs.xml
  project/project.iml
  project/stampee/.gitignore
  project/stampee/.idea/.gitignore
  project/stampee/.idea/misc.xml
  project/stampee/.idea/modules.xml
  project/stampee/.idea/vcs.xml
  project/stampee/src/Main.java
  project/stampee/src/domain/Stamp.java
  project/stampee/stampee.iml
Labels: FEAT🍒, FIX💊

#3 Cafe 도메인 클래스 구현
  project/stampee/src/domain/Cafe.java
Labels: FEAT🍒

#9 [FEAT]: ojdbc6.jar 파일 추가
  project/stampee/.idea/codeStyles/codeStyleConfig.xml
  project/stampee/lib/ojdbc6.jar
  project/stampee/stampee.iml
Labels: FEAT🍒

#11 패키지 구조 생성
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/stampee.iml
  .idea/vcs.xml
  README.md
  project/stampee/.gitignore
  project/stampee/.idea/.gitignore
  project/stampee/.idea/gradle.xml
  project/stampee/.idea/misc.xml
  project/stampee/.idea/uiDesigner.xml
  project/stampee/.idea/vcs.xml
  project/stampee/build.gradle
  project/stampee/gradle/wrapper/gradle-wrapper.jar
  project/stampee/gradle/wrapper/gradle-wrapper.properties
  project/stampee/gradlew
  project/stampee/gradlew.bat
  project/stampee/lib/ojdbc6.jar
  project/stampee/settings.gradle
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/DBConfig.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Coupon.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/domain/Signature.java
  project/stampee/src/main/java/domain/Stamp.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/service/MemberService.java
  project/stampee/src/main/java/view/MemberView.java
Labels: FEAT🍒

#12 [FEAT]: Config 설정
  project/stampee/build.gradle
  project/stampee/lib/ojdbc6.jar
  project/stampee/src/main/java/config/DBConfig.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/repository/MemberRepository.java
Labels: FEAT🍒

#13 테스트 폴더 생성
  project/stampee/src/main/java/domain/Coupon.java
  project/stampee/src/main/java/domain/Stamp.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/test/repository/StampRepositoryTest.java
Labels: FEAT🍒, TEST🕵️

#16 Member, Cafe 도메인 수정
  project/stampee/build.gradle
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Coupon.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/domain/Signature.java
  project/stampee/src/main/java/domain/Stamp.java
  project/stampee/src/main/java/repository/StampRepository.java
Labels: FEAT🍒, FIX💊

#18 [FEAT]: 유저회원가입기능 구현
  project/stampee/src/domain/Member.java
  project/stampee/src/domain/Signature.java
  project/stampee/src/main/java/repository/MemberRepository.java
Labels: FEAT🍒

#15 [FEAT] : 정적인 방법을 통한 메일 전송 기능
  project/stampee/.idea/encodings.xml
  project/stampee/build.gradle
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/service/MailService.java
Labels: FEAT🍒, BE

#20 [FIX]: member repo에서 미사용 객체 제거
  project/stampee/.gitignore
  project/stampee/.idea/gradle.xml
  project/stampee/.idea/misc.xml
  project/stampee/.idea/uiDesigner.xml
  project/stampee/.idea/vcs.xml
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/MemberRepository.java
Labels: FIX💊

#25 [TEST]: StampRepository save 메서드 테스트 코드 작성
  project/stampee/build.gradle
  project/stampee/src/main/java/Template/ConnectionClose.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Stamp.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
  project/stampee/src/test/repository/StampRepositoryTest.java
Labels: FEAT🍒, BE

#22 [FEAT] 카페점주 회원가입 기능 구현
  project/stampee/.gradle/8.5/checksums/checksums.lock
  project/stampee/.gradle/8.5/checksums/md5-checksums.bin
  project/stampee/.gradle/8.5/checksums/sha1-checksums.bin
  project/stampee/.gradle/8.5/dependencies-accessors/dependencies-accessors.lock
  project/stampee/.gradle/8.5/dependencies-accessors/gc.properties
  project/stampee/.gradle/8.5/executionHistory/executionHistory.bin
  project/stampee/.gradle/8.5/executionHistory/executionHistory.lock
  project/stampee/.gradle/8.5/fileChanges/last-build.bin
  project/stampee/.gradle/8.5/fileHashes/fileHashes.bin
  project/stampee/.gradle/8.5/fileHashes/fileHashes.lock
  project/stampee/.gradle/8.5/fileHashes/resourceHashesCache.bin
  project/stampee/.gradle/8.5/gc.properties
  project/stampee/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  project/stampee/.gradle/buildOutputCleanup/cache.properties
  project/stampee/.gradle/buildOutputCleanup/outputFiles.bin
  project/stampee/.gradle/file-system.probe
  project/stampee/.gradle/vcs-1/gc.properties
  project/stampee/.idea/compiler.xml
  project/stampee/.idea/jarRepositories.xml
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/config/DBConfig.class
  project/stampee/build/classes/java/main/config/DBConnectionUtil.class
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Coupon.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/domain/Signature.class
  project/stampee/build/classes/java/main/domain/Stamp.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/classes/java/main/service/MemberService.class
  project/stampee/build/classes/java/main/service/UserService.class
  project/stampee/build/classes/java/main/view/MemberView.class
  project/stampee/build/classes/java/main/view/UserSignupView.class
  project/stampee/build/tmp/compileJava/compileTransaction/stash-dir/CafeRepository.class.uniqueId0
  project/stampee/build/tmp/compileJava/compileTransaction/stash-dir/Main.class.uniqueId1
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/UserService.java
  project/stampee/src/main/java/view/UserSignupView.java
  project/stampee/src/test/repository/CafeRepositoryTest.java
Labels: FEAT🍒, BE

#23 [FEAT]: 총 리뷰수 반환,review id를 이용하여 리뷰 삭제,총 리뷰 조회
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
Labels: FEAT🍒, BE

#26 회원가입 기능 수정
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/MemberRepository.java
Labels: FIX💊

#28 [FEAT]: 스탬프 기능 구현
  project/stampee/.gradle/8.5/checksums/checksums.lock
  project/stampee/.gradle/8.5/checksums/md5-checksums.bin
  project/stampee/.gradle/8.5/checksums/sha1-checksums.bin
  project/stampee/.gradle/8.5/executionHistory/executionHistory.bin
  project/stampee/.gradle/8.5/executionHistory/executionHistory.lock
  project/stampee/.gradle/8.5/fileHashes/fileHashes.bin
  project/stampee/.gradle/8.5/fileHashes/fileHashes.lock
  project/stampee/.gradle/8.5/fileHashes/resourceHashesCache.bin
  project/stampee/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  project/stampee/.gradle/buildOutputCleanup/outputFiles.bin
  project/stampee/.gradle/file-system.probe
  project/stampee/build.gradle
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Coupon.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/domain/Stamp.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/Template/ConnectionClose.java
  project/stampee/src/main/java/domain/Coupon.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Stamp.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
  project/stampee/src/test/java/service/StampServiceTest.java
Labels: FEAT🍒, FIX💊, BE

#39 [FIX]: gitignore 수정
  project/stampee/.gitignore
  project/stampee/.gradle/8.5/checksums/checksums.lock
  project/stampee/.gradle/8.5/checksums/md5-checksums.bin
  project/stampee/.gradle/8.5/checksums/sha1-checksums.bin
  project/stampee/.gradle/8.5/dependencies-accessors/dependencies-accessors.lock
  project/stampee/.gradle/8.5/dependencies-accessors/gc.properties
  project/stampee/.gradle/8.5/executionHistory/executionHistory.bin
  project/stampee/.gradle/8.5/executionHistory/executionHistory.lock
  project/stampee/.gradle/8.5/fileChanges/last-build.bin
  project/stampee/.gradle/8.5/fileHashes/fileHashes.bin
  project/stampee/.gradle/8.5/fileHashes/fileHashes.lock
  project/stampee/.gradle/8.5/fileHashes/resourceHashesCache.bin
  project/stampee/.gradle/8.5/gc.properties
  project/stampee/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  project/stampee/.gradle/buildOutputCleanup/cache.properties
  project/stampee/.gradle/buildOutputCleanup/outputFiles.bin
  project/stampee/.gradle/file-system.probe
  project/stampee/.gradle/vcs-1/gc.properties
  project/stampee/.idea/gradle.xml
  project/stampee/.idea/misc.xml
  project/stampee/.idea/vcs.xml
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/domain/Stamp.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Stamp.java
  project/stampee/src/main/java/exception/ErrorMessage.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/MailService.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
Labels: FIX💊

#36 회원가입 기능에 유효성검사 기능 추가 - 정적 팩터리 메서드화
  project/stampee/.idea/checkstyle-idea.xml
  project/stampee/.idea/modules/stampee.iml
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/.idea/uiDesigner.xml
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/tmp/compileJava/compileTransaction/stash-dir/MemberRepository.class.uniqueId0
  project/stampee/src/main/java/config/AuthConfig.java
  project/stampee/src/main/java/domain/Member.java
Labels: FEAT🍒

#41 [FEAT]: findReviewsByCafeId,updateReview구현
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
Labels: FEAT🍒, BE

#40 [FIX] git 충돌 해결 / [Feat] 회원가입 비밀번호 암호화 처리 및 테스트 코드
  project/stampee/.idea/compiler.xml
  project/stampee/.idea/jarRepositories.xml
  project/stampee/build/classes/java/main/config/DBConfig.class
  project/stampee/build/classes/java/main/config/DBConnectionUtil.class
  project/stampee/build/classes/java/main/domain/Signature.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/classes/java/main/service/MemberService.class
  project/stampee/build/classes/java/main/service/UserService.class
  project/stampee/build/classes/java/main/view/MemberView.class
  project/stampee/build/classes/java/main/view/UserSignupView.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/UserService.java
  project/stampee/src/main/java/util/Encrypt.java
  project/stampee/src/main/java/util/PasswordUtil.java
  project/stampee/src/test/java/repository/CafeRepositoryTest.java
  project/stampee/src/test/repository/CafeRepositoryTest.java
Labels: FEAT🍒, FIX💊, TEST🕵️, BE

#48 [TEST]: 회원가입, 로그인 기능 테스트 코드 구현
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/compileTransaction/stash-dir/MemberRepository.class.uniqueId0
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/test/java/repository/CafeRepositoryTest.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
Labels: TEST🕵️

#42 [FEAT] : JavaFX 설치 및 세팅 -> Map Service 구현 -> MapService JavaFX로 구현 -> API KEY 암호화
  project/stampee/.gitignore
  project/stampee/.idea/encodings.xml
  project/stampee/.idea/misc.xml
  project/stampee/build.gradle
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/service/InviteService.java
  project/stampee/src/main/java/service/KakaoService.java
  project/stampee/src/main/java/service/MailService.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/java/util/ConfigLoader.java
  project/stampee/src/main/resources/MapOutput.fxml
  project/stampee/src/main/resources/logback.xml
Labels: FIX💊, FE

#45 [FEAT]: CafeId로 회원조회기능 추가
  project/stampee/.idea/misc.xml
  project/stampee/.idea/modules/stampee.iml
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/build/classes/java/main/domain/Coupon.class
  project/stampee/build/classes/java/main/domain/Stamp.class
  project/stampee/src/main/java/config/ValidationRules.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
Labels: FEAT🍒

#44 [FEAT]: reviewService구현
  project/stampee/.idea/misc.xml
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/build.gradle
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
Labels: FEAT🍒, BE

#49 [FEAT]: 스탬프 공유 기능 구현
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/exception/ErrorMessage.java
  project/stampee/src/main/java/formatter/MailMessageFormatter.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/MailService.java
  project/stampee/src/main/java/service/MemberService.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
  project/stampee/src/test/java/service/StampServiceTest.java
Labels: FEAT🍒, REFACTOR🎀, TEST🕵️, BE

#53 [REFACTOR] : 보안 강화
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/src/main/java/config/DBConfig.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/service/KakaoService.java
  project/stampee/src/main/java/service/MailService.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/java/util/ConfigLoader.java
Labels: REFACTOR🎀, BE

#54 [FEAT]: 쿠폰 만료 예정이 경우 메일 전송하도록 구현
  project/stampee/.idea/gradle.xml
  project/stampee/.idea/misc.xml
  project/stampee/.idea/modules/stampee.iml
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/domain/Signature.java
  project/stampee/src/main/java/dto/ExpiredCouponDto.java
  project/stampee/src/main/java/formatter/MailMessageFormatter.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/CouponService.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/java/service/Scheduler.java
  project/stampee/src/test/java/repository/CouponRepositoryTest.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
  project/stampee/src/test/java/service/CouponServiceTest.java
Labels: FEAT🍒, BE

#55 [REFACTOR] : ConfigLoader 분리 / [REFACTOR] : 에러 메세지 정리
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/exception/ErrorMessage.java
  project/stampee/src/main/java/service/MailService.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/java/util/ConfigLoader.java
  project/stampee/src/main/java/util/DBConfigLoader.java
  project/stampee/src/main/java/util/GoogleAPIConfigLoader.java
  project/stampee/src/main/java/util/MailAPIConfigLoader.java
  project/stampee/src/main/resources/MapOutput.fxml
  project/stampee/src/main/resources/github_logo.png
  project/stampee/src/main/resources/java_logo.png
  project/stampee/src/main/resources/modern-style.css
  project/stampee/src/main/resources/stampee_logo.png
Labels: REFACTOR🎀, BE

#56 [FEAT]: 보유 중인 스탬프 보여주는 화면 구현
  project/stampee/.idea/modules/stampee.iml
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/StampRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/dto/response/MyStampDto.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/main/resources/MapOutput.fxml
  project/stampee/src/main/resources/stamp.fxml
  project/stampee/src/test/java/repository/CafeRepositoryTest.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
  project/stampee/src/test/java/service/CouponServiceTest.java
  project/stampee/src/test/java/service/StampServiceTest.java
Labels: FEAT🍒, BE, FE

#60 [FEAT]: cafe 회원가입 시 signature 메뉴도 함께 저장
  project/.idea/workspace.xml
  project/stampee/.idea/misc.xml
  project/stampee/src/main/java/controller/SignupController.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Signature.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/java/view/UserSignupView.java
  project/stampee/src/main/resources/MapOutput.fxml
  project/stampee/src/main/resources/config.properties
  project/stampee/src/main/resources/css/modern-style.css
  project/stampee/src/main/resources/css/signup-style.css
  project/stampee/src/main/resources/fxml/MapOutput.fxml
  project/stampee/src/main/resources/fxml/signup.fxml
  project/stampee/src/main/resources/image/github_logo.png
  project/stampee/src/main/resources/image/java_logo.png
  project/stampee/src/main/resources/image/stampee_logo.png
  project/stampee/src/test/java/repository/CafeRepositoryTest.java
  project/stampee/src/test/java/repository/MemberRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
  project/stampee/src/test/java/repository/StampRepositoryTest.java
Labels: FEAT🍒, REFACTOR🎀, BE

#58 회원가입, 로그인 화면구현
  project/stampee/.idea/gradle.xml
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/ValidationRules.java
  project/stampee/src/main/java/controller/AccountController.java
  project/stampee/src/main/java/view/MemberView.java
  project/stampee/src/main/resources/stampee templates.fxml
  project/stampee/src/main/resources/templates/account/LoginPage.fxml
  project/stampee/src/main/resources/templates/account/SignUpPageMain.fxml
  project/stampee/src/main/resources/templates/reusables/Header.fxml
  project/stampee/src/main/resources/templates/reusables/LogoArea.fxml
Labels: FEAT🍒, FIX💊, FE

#63 [FEAT]: ReviewListView, ReviewController구현 및 테스트 수정
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/java/view/ReviewView.java
  project/stampee/src/main/resources/reviewListView.fxml
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
Labels: FEAT🍒, FIX💊, TEST🕵️, BE, FE

#62 [FEAT]: 쿠폰 모아보는 화면 구현
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/NumberPadController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/dto/response/MyCouponDto.java
  project/stampee/src/main/java/dto/response/MyStampDto.java
  project/stampee/src/main/java/formatter/PhoneNumberFormatter.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/java/service/CouponService.java
  project/stampee/src/main/java/service/InviteService.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/main/java/service/UserService.java
  project/stampee/src/main/java/view/CouponView.java
  project/stampee/src/main/resources/CouponPage.css
  project/stampee/src/main/resources/CouponPage.fxml
  project/stampee/src/main/resources/image/gift-card.png
  project/stampee/src/main/resources/numberPad.css
  project/stampee/src/main/resources/numberPad.fxml
  project/stampee/src/main/resources/stamp.fxml
  project/stampee/src/test/java/repository/CouponRepositoryTest.java
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
Labels: FEAT🍒, BE, FE

#64 [REFACTOR]: login 매개변수 수정
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/test/java/repository/CafeRepositoryTest.java
Labels: REFACTOR🎀

#65 [FEAT]: 리뷰 화면 stamp.fxml 파일에 추가
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/domain/Review.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/classes/java/main/repository/MemberRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/controller/AccountController.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/NumberPadController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/SignupController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Review.java
  project/stampee/src/main/java/domain/Signature.java
  project/stampee/src/main/java/dto/response/MyCouponDto.java
  project/stampee/src/main/java/dto/response/MyStampDto.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/java/service/CouponService.java
  project/stampee/src/main/java/service/MailService.java
  project/stampee/src/main/java/service/MapService.java
  project/stampee/src/main/java/service/ReviewService.java
  project/stampee/src/main/java/util/DBConfigLoader.java
  project/stampee/src/main/java/util/Encrypt.java
  project/stampee/src/main/java/util/GoogleAPIConfigLoader.java
  project/stampee/src/main/java/util/MailAPIConfigLoader.java
  project/stampee/src/main/java/view/ReviewView.java
  project/stampee/src/main/resources/css/CouponPage.css
  project/stampee/src/main/resources/css/numberPad.css
  project/stampee/src/main/resources/fxml/CouponPage.fxml
  project/stampee/src/main/resources/fxml/MapOutput.fxml
  project/stampee/src/main/resources/fxml/numberPad.fxml
  project/stampee/src/main/resources/fxml/stamp.fxml
  project/stampee/src/main/resources/reviewListView.fxml
  project/stampee/src/main/resources/templates/account/LoginPage.fxml
  project/stampee/src/main/resources/templates/account/SignUpPageMain.fxml
  project/stampee/src/test/java/repository/ReviewRepositoryTest.java
Labels: FEAT🍒, REFACTOR🎀, FE

#70 [FEAT]: CAFE 회원가입 fxml파일 생성 및 DB연결
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/src/main/java/controller/CafeSignupController.java
  project/stampee/src/main/java/controller/UserSignupController.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/Member.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/resources/templates/account/CafeSignupPage.fxml
  project/stampee/src/main/resources/templates/account/UserSignupPage.fxml
  project/stampee/src/main/resources/templates/reusables/Header.fxml
  project/stampee/src/main/resources/templates/reusables/LogoArea.fxml
Labels: FEAT🍒, REFACTOR🎀, BE, FE

#73 [FEAT]: 스탬프 화면, 리뷰 화면이랑 합치기, footer
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/view/ReviewView.java
  project/stampee/src/main/resources/css/modern-style.css
  project/stampee/src/main/resources/fxml/CouponPage.fxml
  project/stampee/src/main/resources/fxml/reviewListView.fxml
  project/stampee/src/main/resources/fxml/stamp.fxml
  project/stampee/src/main/resources/templates/account/LoginPage.fxml
  project/stampee/src/main/resources/templates/account/SignUpPageMain.fxml
  project/stampee/src/main/resources/templates/reusables/Header.fxml
  project/stampee/src/main/resources/templates/reusables/LogoArea.fxml
  project/stampee/src/main/resources/templates/reusables/footer.fxml
Labels: FEAT🍒, FE

#68 [FEAT] : 공유 성공/실패 이벤트 팝업 기능 추가
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/domain/Member.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/controller/NumberPadController.java
  project/stampee/src/main/java/controller/ShareCompleteController.java
  project/stampee/src/main/java/controller/ShareFailController.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/InviteService.java
  project/stampee/src/main/java/util/DBConfigLoader.java
  project/stampee/src/main/resources/css/CouponPage.css
  project/stampee/src/main/resources/css/shareComplete.css
  project/stampee/src/main/resources/font/BagelFatOne-Regular.ttf
  project/stampee/src/main/resources/font/EastSeaDokdo-Regular.ttf
  project/stampee/src/main/resources/font/GasoekOne-Regular.ttf
  project/stampee/src/main/resources/font/Jua-Regular.ttf
  project/stampee/src/main/resources/font/SingleDay-Regular.ttf
  project/stampee/src/main/resources/fxml/shareComplete.fxml
  project/stampee/src/main/resources/fxml/shareFailed.fxml
  project/stampee/src/main/resources/fxml/stampee templates.fxml
Labels: FEAT🍒, FE

#74 [FEAT]: 특정 카페 리뷰만 조회하도록 수정
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/domain/LoginSession.java
  project/stampee/src/main/java/dto/LoggedMemberDto.java
  project/stampee/src/main/java/exception/ErrorMessage.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/service/InviteService.java
  project/stampee/src/main/resources/css/modern-style.css
  project/stampee/src/main/resources/fxml/stampee templates.fxml
  project/stampee/src/main/resources/templates/account/CafeSignupPage.fxml
Labels: FEAT🍒, BE, FE

#75 [fix] 회원가입 메인 페이지에서 카페/일반 회원 회원가입 페이지 이동 처리
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/AccountController.java
  project/stampee/src/main/java/controller/LoginController.java
  project/stampee/src/main/java/controller/SignupMainController.java
  project/stampee/src/main/java/controller/UserSignupController.java
  project/stampee/src/main/java/domain/LoginSession.java
  project/stampee/src/main/java/dto/LoggedMemberDto.java
  project/stampee/src/main/resources/templates/account/LoginPage.fxml
  project/stampee/src/main/resources/templates/account/SignUpPageMain.fxml
  project/stampee/src/main/resources/templates/account/UserSignupPage.fxml
Labels: FIX💊, FE

#78 [FEAT] : 적립 요청 기능 추가
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/resources/css/keypadView.css
  project/stampee/src/main/resources/font/BagelFatOne-Regular.ttf
  project/stampee/src/main/resources/font/EastSeaDokdo-Regular.ttf
  project/stampee/src/main/resources/font/GasoekOne-Regular.ttf
  project/stampee/src/main/resources/font/SingleDay-Regular.ttf
  project/stampee/src/main/resources/fxml/CouponPage.fxml
  project/stampee/src/main/resources/fxml/keypadView.fxml
Labels: FEAT🍒, BE, FE

#81 [FEAT]: 헤더 리뷰 이동하도록 구현
  project/stampee/.idea/encodings.xml
  project/stampee/.idea/gradle.xml
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/build.gradle
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/config/ConnectionClose.java
  project/stampee/src/main/java/config/DBConnectionUtil.java
  project/stampee/src/main/java/controller/CafeSignupController.java
  project/stampee/src/main/java/controller/CouponController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/controller/LoginController.java
  project/stampee/src/main/java/controller/NumberPadController.java
  project/stampee/src/main/java/controller/ReviewController.java
  project/stampee/src/main/java/controller/SignupMainController.java
  project/stampee/src/main/java/controller/StampController.java
  project/stampee/src/main/java/controller/UserSignupController.java
  project/stampee/src/main/java/domain/LoginSession.java
  project/stampee/src/main/java/domain/ReviewType.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/repository/CouponRepository.java
  project/stampee/src/main/java/repository/MemberRepository.java
  project/stampee/src/main/java/repository/ReviewRepository.java
  project/stampee/src/main/java/repository/StampRepository.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/main/java/util/DBConfigLoader.java
  project/stampee/src/main/java/util/Encrypt.java
  project/stampee/src/main/java/view/ReviewView.java
  project/stampee/src/main/resources/fxml/keypadView.fxml
  project/stampee/src/main/resources/fxml/reviews.fxml
Labels: FEAT🍒, FIX💊, BE, FE

#80 [FEAT]: Login한 회원 정보 저장
  project/stampee/.idea/modules/stampee.main.iml
  project/stampee/build.gradle
  project/stampee/build/classes/java/main/domain/Cafe.class
  project/stampee/build/classes/java/main/repository/CafeRepository.class
  project/stampee/logs/app.log
  project/stampee/src/main/java/controller/LoginController.java
  project/stampee/src/main/java/controller/SignupController.java
  project/stampee/src/main/java/controller/UserSignupController.java
  project/stampee/src/main/java/domain/Cafe.java
  project/stampee/src/main/java/domain/LoginSession.java
  project/stampee/src/main/java/dto/response/LoggedCafeDto.java
  project/stampee/src/main/java/dto/response/LoggedMemberDto.java
  project/stampee/src/main/java/repository/CafeRepository.java
  project/stampee/src/main/java/service/CafeService.java
  project/stampee/src/main/java/util/PasswordUtil.java
  project/stampee/src/main/resources/logback.xml
  project/stampee/src/main/resources/templates/account/CafeSignupPage.fxml
  project/stampee/src/main/resources/templates/account/LoginPage.fxml
  project/stampee/src/test/java/repository/CafeRepositoryTest.java
Labels: FEAT🍒, FIX💊, BE

#79 [FEAT] : Stamp 적립 개수 입력 기능 추가
  project/stampee/build/classes/java/main/Main.class
  project/stampee/build/tmp/compileJava/previous-compilation-data.bin
  project/stampee/src/main/java/controller/KeypadController.java
  project/stampee/src/main/java/service/StampService.java
  project/stampee/src/main/resources/css/common.css
  project/stampee/src/main/resources/css/keypadView.css
  project/stampee/src/main/resources/fxml/CouponPage.fxml
  project/stampee/src/main/resources/fxml/keypadView.fxml
Labels: FEAT🍒, BE

#83 [FEAT]: 로그아웃 버튼 클릭 시 세션 초기화 및 로그인 화면으로 변환
  project/stampee/src/main/java/Main.java
  project/stampee/src/main/java/controller/CafeLoginController.java
  project/stampee/src/main/java/controller/HeaderController.java
  project/stampee/src/main/java/domain/LoginSession.java
  project/stampee/src/main/java/dto/response/LoggedCafeDto.java
  project/stampee/src/main/java/session/CafeSession.java
  project/stampee/src/main/resources/templates/account/LoginPage.fxml
  project/stampee/src/main/resources/templates/reusables/Header.fxml
Labels: FEAT🍒, BE, FE
